### ISSUE TITLE
Laptop ideas

### ISSUE THREAD

**Issue by rpodcast** [romainfrancois/support#1]
Feel free to disregard but there are more cost-friendly alternatives to a macbook made to run linux that you may want to consider (based on recommendations from the linux podcasts I listen to):
* [Entroware](https://www.entroware.com/store/) produce linux laptops and desktops (based in UK) and I believe they ship to most of Europe.  In particular the laptops range from macbook-like (such as the [Apollo](https://www.entroware.com/store/apollo)) to mobile workstations (see the [Athena](https://www.entroware.com/store/athena))
* Dell is making solid linux-friendly laptops such as the [XPS 13 developer edition](http://www.dell.com/en-us/work/shop/cty/pdp/spd/xps-13-9360-laptop) .  I'm not sure if the shipping cost would be a deal-breaker but it still may be worth a look.

**Comment by romainfrancois** [comment]
Thanks for the suggestion, but I'm too much of an 🍎 fanboy at this point.
